---

name: config

on:
  workflow_call:
    inputs:
      platforms:
        description: "The platforms to build (CSV)"
        default: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le
        required: false
        type: string
    outputs:
      image_name:
        description: "The Docker image name"
        value: felddy/foundryvtt
      data_artifact_name:
        description: "The name of the test data artifact"
        value: test-output
      data_artifact_path:
        description: "The path to include in the test data artifact"
        value: data
      image_artifact_name_stem:
        description: "The name of the image archives artifact"
        value: image-archive
      platforms:
        description: "The platforms to build (CSV)"
        value: ${{ inputs.platforms }}
      platforms_json:
        description: "The platforms to build (JSON)"
        value: ${{ jobs.csv-to-json.outputs.json }}
      sbom_artifact_name_stem:
        description: "The stem name for sbom artifacts"
        value: sbom
      test_platform:
        description: "The platform to use for testing"
        value: linux/amd64

permissions:
  contents: read

jobs:
  csv-to-json:
    name: "Convert CSV to JSON"
    uses: felddy/reusable-workflows/.github/workflows/csv-to-json.yml@v2
    with:
      csv: ${{ inputs.platforms }}
